enum ScreenRoutes {
  onboarding("/"),
  signIn("/signIn"),
  register("/register"),
  main("/navigation"),
  notifications("/notifications"),
  jobMarket("/jobMarket"),
  employers("/employers"),
  careerMaterials("/careerMaterials"),
  careerArticle("/careerArticle"),
  applicationDetails("/applicationDetails"),
  interviewDetails("/interviewDetails"),
  settings("/settings"),
  createFeedback("/createFeedback"),
  feedbackList("/feedbackList"),
  postingDetails("/postingDetails"),
  postingDetailsWithoutApply("/postingDetailsWithoutApply"),
  apply("/apply"),
  editProfile("/editProfile"),
  options("/options"),
  editProfileTextSection("/editProfileTextSection"),
  editExperienceListSection("/editExperienceListSection"),
  addExperienceListSection("/addExperienceTextSection"),
  editEducationListSection("/editEducationListSection"),
  addEducationListSection("/addEducationListSection"),
  addOtherExperienceListSection("/addOtherExperienceListSection"),
  editOtherExperienceListSection("editOtherExperienceListSection"),
  employerDetails("/employerDetails"),
  reportProfile("/reportProfile"),
  reportFeedback("/reportFeedback"),
  pickTimeSlot("/pickTimeSlot");
  final String route;
  const ScreenRoutes(this.route);
}